name: noteapp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can specify the Node.js version you need

      - name: Install dependencies
        run: npm install

     # - name: Run tests
      #  run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        with:
          args: >
            -Dsonar.projectKey=chetna0207  
            -Dsonar.organization=chetna0207  
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions="**/*.test.js,**/*.spec.js"
